Added OfficesAPI to Project
FileBin/InnoClinic pull request #1
Opened 2024-04-01 15:11 UTC by FileBin

* Created Offices Api using Onion architecture
* Layers
  1. Domain
    > Contains business entities
  2. Application
    > Contains Service implementation
  3. Application.Contracts
    > Contains Service Interfaces and Data-Transfer Models
  4. Infrastructure
    > Contains Database Logic
  5. Presentation
    > Contains Controller that handles requests for service

2024-04-01 17:44 UTC, artem-gck requested changes
Мне очень понравилось
Качество кода на высоте, спасибо за это!
Глянь в комменты что оставил, можем обсудить что и как, если что-то непонятно

Из больших прям изменений что я бы хотел  видеть
1. Выделение Shared в Nuget
2. Dockerfile

2024-04-01 17:44 UTC, artem-gck commented on docker-compose.yml
> +
Добавй добавим отдельный файл Dockerfile для офисов, чтобы можно было отдельно контейнер запустить
Вне докеркомпоуза и вижлы

2024-04-01 17:44 UTC, artem-gck commented on scripts/configure_secrets.sh
> +cat <<EOF | dotnet user-secrets set --id '1c6837c9-a327-43b0-9139-f864c65c0c95'
Такой вариант добавления секретов это хорошо
Но если у тебя есть вижла, потому что эти секреты храняться на компе где ты запускаешь этот проект и подвязаны к вижле
Хоть это и не очень секьюрно, но давай просто создадим файл .env в котором будем хранить секреты
Можно написать скриптик который будет инкриптить сикреты перед пушем, а чтобы запустить нужно будет запустить самому скрипт чтобы расшифровать данные
Ключ от данных можно хранить где-то у себя, что-то такое

2024-04-01 17:44 UTC, artem-gck commented on Backend/Shared/Misc/Middleware/ExceptionHandler.cs
> +internal sealed class ExceptionHandler(IProblemDetailsService problemDetailsService) : IExceptionHandler {
Крутое решение нашел
Часто пишут свои мидлваре для этого полностью, не используя встроенные сервисы
Оставь так, так прям хорошо

2024-04-01 17:44 UTC, artem-gck commented on Backend/Shared/Filebin.Common.Util
Думаю что можно удалить, а то тут пусто)
Ну или там еще что-то будет?

2024-04-01 17:44 UTC, artem-gck commented on Backend/Shared/Exceptions/Shared.Exceptions.csproj
Есть предложение прокинуть все папку Shared и все проекты что в ней в отдельный репозиторий
И сделать их как NuGet пакеты свои
Там еще напишем пайплан который сам будет все билдить и пушить в NuGet

2024-04-01 17:44 UTC, artem-gck commented on Backend/OfficesAPI/Application.Contracts/Models/AddressDto.cs
Для большей читаемости давай поделим эти модели на 2 папки
Requests and Responses
В папке Requests будут лежать те модели которые приходят в контроллер
В папке Responses будут лежать те модели которые контроллер отдает клиенту

И по их нэймингам - AddressDto -> AddressRequest
Так если станет много моделей будет легче понять где какие

2024-04-01 17:44 UTC, artem-gck commented on Backend/OfficesAPI/Infrastructure/Repository/OfficeRepository.cs
> +            .AsNoTracking()
Отлично что не забыл поставить AsNoTracking()

2024-04-01 17:44 UTC, artem-gck commented on Backend/OfficesAPI/Tests/TestsCrud.cs
Вообще проект с тестами по Best practices должен копировать структуру тестируемого проекта
То есть даже учитывая то что у тебя тестов немного то этот файл должен быть по пути 
Backend/OfficesAPI/Tests/Application/Services/OfficeServiceTests.cs

2024-04-01 17:44 UTC, artem-gck commented on Backend/OfficesAPI/Tests/TestsCrud.cs
Добавь еще парочку тестов на то, что будет если officeRepository.GetByIdAsync вернет null
Чтобы проверить как выпадают твои exceptions

2024-04-01 17:45 UTC, artem-gck commented
Ааа, и тут еще конфликт, он не даст смерджить
Поиграемся теперь с гитом
Тебе нужно исправить этот конфликт и вмерджить еще в эту ветку development
Если хочешь, то можем вместе это сделать

2024-04-01 20:16 UTC, FileBin commented on Backend/Shared/Filebin.Common.Util
а, да тут был сабмодуль я забыл папку от него убрать

2024-04-01 20:22 UTC, FileBin commented on scripts/configure_secrets.sh
> +source .env
В этой строке берется .env и потом из него переменные перезаливаются в секреты.
Я могу в целом переделать чтобы у меня сразу переменные брались из .env без использования secrets
Просто раньше так делал и решил не придумывать нового

2024-04-17 13:10 UTC, artem-gck approved these changes

2024-04-17 13:10 UTC, merged